analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.jsx"
    - "**/node_modules/**"
    - "**/.dart_tool/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/build/**"
