/// Synthetic event types for React.
///
/// These extension types provide type-safe wrappers around React's
/// SyntheticEvent objects.
library;

import 'dart:js_interop';

// =============================================================================
// Base SyntheticEvent
// =============================================================================

/// A cross-browser wrapper around the browser's native event.
///
/// It has the same interface as the browser's native event, including
/// [stopPropagation] and [preventDefault], except the events work identically
/// across all browsers.
///
/// See: https://reactjs.org/docs/events.html#syntheticevent
extension type SyntheticEvent._(JSObject _) implements JSObject {
  /// Creates a SyntheticEvent from a raw JSObject.
  factory SyntheticEvent.fromJs(JSObject jsObject) = SyntheticEvent._;

  /// Indicates whether the Event bubbles up through the DOM or not.
  external bool get bubbles;

  /// Indicates whether the Event is cancelable or not.
  external bool get cancelable;

  /// Identifies the current target for the event.
  external JSAny? get currentTarget;

  /// Indicates whether or not preventDefault was called on the event.
  external bool get defaultPrevented;

  /// Indicates which phase of the Event flow is currently being evaluated.
  external num get eventPhase;

  /// Is true when the Event was generated by a user action.
  external bool get isTrusted;

  /// The native browser event this wraps.
  external JSAny? get nativeEvent;

  /// A reference to the object that dispatched the event.
  external JSAny? get target;

  /// Returns the time (in milliseconds) at which the Event was created.
  external num get timeStamp;

  /// Returns a string containing the type of event.
  external String get type;

  /// Prevents further propagation of the current event.
  external void stopPropagation();

  /// Cancels the Event if it is cancelable.
  external void preventDefault();

  /// Tells the user agent that if the event does not get explicitly handled,
  /// its default action should not be taken as it normally would be.
  external void persist();

  /// Whether or not the event has been persisted.
  external bool get isPersistent;
}

// =============================================================================
// SyntheticClipboardEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a ClipboardEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent
extension type SyntheticClipboardEvent._(JSObject _)
    implements SyntheticEvent {
  /// Creates a SyntheticClipboardEvent from a raw JSObject.
  factory SyntheticClipboardEvent.fromJs(JSObject jsObject) =
      SyntheticClipboardEvent._;

  /// Holds a DataTransfer object with the data affected by the clipboard
  /// operation.
  external JSAny? get clipboardData;
}

// =============================================================================
// SyntheticKeyboardEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a KeyboardEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent
extension type SyntheticKeyboardEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticKeyboardEvent from a raw JSObject.
  factory SyntheticKeyboardEvent.fromJs(JSObject jsObject) =
      SyntheticKeyboardEvent._;

  /// Whether the Alt key was active when this event was generated.
  external bool get altKey;

  /// The character value of the key.
  @JS('char')
  external String get char;

  /// Whether the Ctrl key was active when this event was generated.
  external bool get ctrlKey;

  /// A locale string indicating the locale the keyboard is configured for.
  external String get locale;

  /// The location of the key on the keyboard or other input device.
  external num get location;

  /// The key value of the key represented by this event.
  external String get key;

  /// Whether the Meta key was active when this event was generated.
  external bool get metaKey;

  /// Whether the key is being held down such that it is automatically
  /// repeating.
  external bool get repeat;

  /// Whether the Shift key was active when this event was generated.
  external bool get shiftKey;

  /// A numerical code identifying the unmodified value of the pressed key.
  external num get keyCode;

  /// The Unicode reference number of the key.
  external num get charCode;

  /// Returns true if the specified modifier key was pressed.
  external bool getModifierState(String key);
}

// =============================================================================
// SyntheticCompositionEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a CompositionEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent
extension type SyntheticCompositionEvent._(JSObject _)
    implements SyntheticEvent {
  /// Creates a SyntheticCompositionEvent from a raw JSObject.
  factory SyntheticCompositionEvent.fromJs(JSObject jsObject) =
      SyntheticCompositionEvent._;

  /// The characters generated by the input method that raised this event.
  external String get data;
}

// =============================================================================
// SyntheticFocusEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a FocusEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent
extension type SyntheticFocusEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticFocusEvent from a raw JSObject.
  factory SyntheticFocusEvent.fromJs(JSObject jsObject) =
      SyntheticFocusEvent._;

  /// A secondary target for this event.
  external JSAny? get relatedTarget;
}

// =============================================================================
// SyntheticFormEvent
// =============================================================================

/// A SyntheticEvent wrapper that represents a form event.
extension type SyntheticFormEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticFormEvent from a raw JSObject.
  factory SyntheticFormEvent.fromJs(JSObject jsObject) = SyntheticFormEvent._;
}

// =============================================================================
// SyntheticMouseEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a MouseEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent
extension type SyntheticMouseEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticMouseEvent from a raw JSObject.
  factory SyntheticMouseEvent.fromJs(JSObject jsObject) =
      SyntheticMouseEvent._;

  /// Whether the Alt key was down when this event was fired.
  external bool get altKey;

  /// The button number that was pressed when this event was fired.
  external num get button;

  /// The buttons being depressed when this event was fired.
  external num get buttons;

  /// The X coordinate of the mouse pointer in local (DOM content) coordinates.
  external num get clientX;

  /// The Y coordinate of the mouse pointer in local (DOM content) coordinates.
  external num get clientY;

  /// Whether the Ctrl key was active when this event was generated.
  external bool get ctrlKey;

  /// Whether the Meta key was down when this event was fired.
  external bool get metaKey;

  /// The X coordinate of the mouse pointer relative to the whole document.
  external num get pageX;

  /// The Y coordinate of the mouse pointer relative to the whole document.
  external num get pageY;

  /// The secondary target for this event, if there is one.
  external JSAny? get relatedTarget;

  /// The X coordinate of the mouse pointer in global (screen) coordinates.
  external num get screenX;

  /// The Y coordinate of the mouse pointer in global (screen) coordinates.
  external num get screenY;

  /// Whether the Shift key was active when this event was generated.
  external bool get shiftKey;

  /// Returns true if the specified modifier key was pressed.
  external bool getModifierState(String key);
}

// =============================================================================
// SyntheticDragEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a DragEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/DragEvent
extension type SyntheticDragEvent._(JSObject _) implements SyntheticMouseEvent {
  /// Creates a SyntheticDragEvent from a raw JSObject.
  factory SyntheticDragEvent.fromJs(JSObject jsObject) = SyntheticDragEvent._;

  /// The data that is transferred during a drag and drop operation.
  external JSAny? get dataTransfer;
}

// =============================================================================
// SyntheticPointerEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a PointerEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent
extension type SyntheticPointerEvent._(JSObject _)
    implements SyntheticMouseEvent {
  /// Creates a SyntheticPointerEvent from a raw JSObject.
  factory SyntheticPointerEvent.fromJs(JSObject jsObject) =
      SyntheticPointerEvent._;

  /// A unique identifier for the pointer causing the event.
  external num get pointerId;

  /// The width of the contact geometry of the pointer.
  external num get width;

  /// The height of the contact geometry of the pointer.
  external num get height;

  /// The normalized pressure of the pointer input.
  external num get pressure;

  /// The normalized tangential pressure of the pointer input.
  external num get tangentialPressure;

  /// The plane angle between the Y-Z plane and the pointer axis.
  external num get tiltX;

  /// The plane angle between the X-Z plane and the pointer axis.
  external num get tiltY;

  /// The clockwise rotation of the pointer around its major axis.
  external num get twist;

  /// Indicates the device type that caused this event.
  external String get pointerType;

  /// Indicates if the pointer represents the primary pointer of this type.
  external bool get isPrimary;
}

// =============================================================================
// SyntheticTouchEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a TouchEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent
extension type SyntheticTouchEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticTouchEvent from a raw JSObject.
  factory SyntheticTouchEvent.fromJs(JSObject jsObject) =
      SyntheticTouchEvent._;

  /// Whether the Alt key was down when this event was fired.
  external bool get altKey;

  /// All Touch objects whose states changed between the previous event and
  /// this one.
  external JSArray get changedTouches;

  /// Whether the Ctrl key was down when this event was fired.
  external bool get ctrlKey;

  /// Whether the Meta key was down when this event was fired.
  external bool get metaKey;

  /// Whether the Shift key was down when this event was fired.
  external bool get shiftKey;

  /// All Touch objects that are in contact with the surface and started on
  /// the target element.
  external JSArray get targetTouches;

  /// All Touch objects representing all current points of contact.
  external JSArray get touches;

  /// Returns true if the specified modifier key was pressed.
  external bool getModifierState(String key);
}

// =============================================================================
// SyntheticTransitionEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a TransitionEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent
extension type SyntheticTransitionEvent._(JSObject _)
    implements SyntheticEvent {
  /// Creates a SyntheticTransitionEvent from a raw JSObject.
  factory SyntheticTransitionEvent.fromJs(JSObject jsObject) =
      SyntheticTransitionEvent._;

  /// The name of the CSS property associated with the transition.
  external String get propertyName;

  /// The amount of time the transition has been running.
  external num get elapsedTime;

  /// The name of the pseudo-element the animation runs on.
  external String get pseudoElement;
}

// =============================================================================
// SyntheticAnimationEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by an AnimationEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/AnimationEvent
extension type SyntheticAnimationEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticAnimationEvent from a raw JSObject.
  factory SyntheticAnimationEvent.fromJs(JSObject jsObject) =
      SyntheticAnimationEvent._;

  /// The value of the animation-name that generated the animation.
  external String get animationName;

  /// The amount of time the animation has been running.
  external num get elapsedTime;

  /// The name of the pseudo-element the animation runs on.
  external String get pseudoElement;
}

// =============================================================================
// SyntheticUIEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a UIEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/UIEvent
extension type SyntheticUIEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticUIEvent from a raw JSObject.
  factory SyntheticUIEvent.fromJs(JSObject jsObject) = SyntheticUIEvent._;

  /// Details about the event, depending on the event type.
  external num get detail;

  /// A WindowProxy that contains the view that generated the event.
  external JSAny? get view;
}

// =============================================================================
// SyntheticWheelEvent
// =============================================================================

/// A SyntheticEvent wrapper backed by a WheelEvent.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent
extension type SyntheticWheelEvent._(JSObject _)
    implements SyntheticMouseEvent {
  /// Creates a SyntheticWheelEvent from a raw JSObject.
  factory SyntheticWheelEvent.fromJs(JSObject jsObject) =
      SyntheticWheelEvent._;

  /// The horizontal scroll amount.
  external num get deltaX;

  /// The unit of the delta values' scroll amount.
  external num get deltaMode;

  /// The vertical scroll amount.
  external num get deltaY;

  /// The scroll amount for the z-axis.
  external num get deltaZ;
}

// =============================================================================
// SyntheticInputEvent
// =============================================================================

/// A SyntheticEvent wrapper for input events.
///
/// See: https://developer.mozilla.org/en-US/docs/Web/API/InputEvent
extension type SyntheticInputEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticInputEvent from a raw JSObject.
  factory SyntheticInputEvent.fromJs(JSObject jsObject) =
      SyntheticInputEvent._;

  /// The data being inserted or deleted.
  external String? get data;

  /// The type of change for the input event.
  external String get inputType;
}

// =============================================================================
// SyntheticChangeEvent
// =============================================================================

/// A SyntheticEvent wrapper for change events.
extension type SyntheticChangeEvent._(JSObject _) implements SyntheticEvent {
  /// Creates a SyntheticChangeEvent from a raw JSObject.
  factory SyntheticChangeEvent.fromJs(JSObject jsObject) =
      SyntheticChangeEvent._;
}
